.cuda-template:
  variables:
    CMAKE_PRECISION_OPTIONS: "-DGMX_DOUBLE=OFF"
    CUDA_BASE_VERSION: ""
    BUILD_DIR: build-cuda
    CMAKE_EXTRA_OPTIONS: -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda/
    CMAKE_GPU_OPTIONS: -DGMX_GPU=ON

